= Improving Hardware Register Documentation Tooling
Josh Geden <joshua.geden@duke.edu>; Rob Donnelly <robert.donnelly@jpl.nasa.gov>
:toc:
:imagesdir: images
:sectnums:
// :toclevels: 4
// :titlepage:
// :doctype: book
// :chapter-label:
// :hardbreaks-option:

== Abstract

Hardware documentation at JPL has historically been generated by hand and accessed through shared PDF documents.
This can lead to issues where the documentation does not keep pace with the actual hardware implementation.
It also leads to documents that are difficult to use and lack the necessary features to accelerate the hardware debugging process.
To address these issues, a hardware documentation tool called _regvue_ was created.
This tool is available as both a web and desktop application and is capable of building advanced documentation sites from data files that implement the Register Description Format.
Documentation can now be automatically updated by making changes to the data files, ensuring that engineers always have access to current information in an easy-to-read format.
Features such as full-text search and automatic bit encoding/decoding are also provided.
Future features will include enabling _regvue_ to interface with hardware and directly read and decode register values.
By providing higher quality documentation and advanced features with _regvue_, hardware engineers will spend significantly less time during the debugging process.


== Introduction

When engineers need to consult hardware documentation, they traditionally have turned to PDF or Word documents created and maintained by design engineers that are typically hosted on internal file-sharing websites.
From these websites, users can either open the document as an online file preview or they can download the file and open it locally.
Because viewing these types of files online lacks a lot of features and is typically slower to use, most users download these documentation files and use them locally.

This creates an issue when the design engineer uploads a new version of the documentation but users continue to use their locally-downloaded documentation file, which has since become outdated.
This mismatch can be difficult to notice and can lead to wasted time when trying to target a specific hardware implementation that no longer exists.

The documentation provided by these Word documents is also static and does not support the actual development and debugging workflow of hardware engineers.
For example, when developing or debugging hardware, engineers are often interested in the specific value of a hardware register.
This register may consist of numerous fields where the specific value of each individual field depends on its position in the overall register.
The overall register value may also be read out as little or big endian depending of the device under test (DUT).
It might also be outputted as a hexadecimal value but in order to understand what certain register fields contain, the user will have to convert the value to binary.
This manual manipulation and conversion of field values is incredibly error-prone and unnecessarily increases the complexity of the already complex hardware development and debugging process.

These issues with JPL's existing hardware documentation strategy is what inspired to the development of _regvue_.
Available as both web and desktop applications, _regvue_ supports a design-agnostic JSON schema called the Register Description Format (RDF).
Users can upload RDF files and _regvue_ will produce a full documentation website, with all the features of classic online technical documentation sites. 

* IMAGE *

_regvue_ also provides an interactive bit table where users can input and manipulate register values.

* IMAGE *

Text.
The paper should begin by providing background, presenting the nature and scope of the problem being investigated, and giving rationale for the work.
The main conclusions should be stated briefly in this section.
This section should be accessible to readers in any discipline (including non-science fields) and readers for whom English is not a first language.

== Methods

Describe the schema
Why is a schema important?  What is its purpose?
Versioning – How do we make breaking changes to schema gracefully?
Validation
Reference the schema documentation
Optionally mention and reference CMSIS-SVD which provided some inspiration for RDF.
How are they different?  How are they the same?

Methods.
This section should be subdivided by short headings referring to the technique being used or the experiment being explained.
This section is directed toward scientists in the author's field.

== Results

Following this introductory section, the findings should be described concisely with brief descriptions of the methodology when necessary.
The text should finish with a discussion of the results.
The implications of the research, relation to other work in the author's lab, and future research directions should be included in this section.
Even though this section may be technical, it should not be obtuse.


Figures.
Include figures whenever possible to illustrate your points.
Explanatory diagrams may help explain background information (pictures from textbooks are fine).
Carefully choose your image size, font size, line widths, and labels to ensure that your figures are clear.
Plot theory and experiment on the same graph and redraw screen photos.
All figures should be accompanied by explanatory captions.


Favor fewer information packed screenshots that show multiple things at once.
Use annotations to point out relevant portions. (e.g. recent searches + search suggestions)
Consider creating an image that shows the link between the schema and the render (e.g.root.display_name and where it is rendered in the app)

References.
Authors are responsible for the accuracy of references.
References should be numbered sequentially as they appear in the text and should be listed at the end of the paper.
Reference numbers should be in superscript when cited in the text.

Acknowledgments.
Acknowledge your mentor and all other individuals who provided technical assistance, and the individuals, organizations, grants, or contracts from whom you received financial support.
Students should be sure to include the names of their financial sponsors.


== Appendix

Appendices.
Large data files, catalogs, tables, diagrams, and archival information may be included in 'Appendices' at the end of the paper.
